name:                quantum-algorithms
version:             0.1.0.0
github:              "mx-psi/quantum-algorithms"
license:             BSD3
author:              "Pablo Baeyens"
maintainer:          "xxxx@xxxx"
copyright:           "2019 Pablo Baeyens"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/mx-psi/quantum-algorithms#readme>

dependencies:
- base >= 4.7 && < 5
- quipperlib == 0.1.0.0
- directory >= 1.1
- containers >=0.5 && < 0.7
- filepath >= 1.4 && < 2
- easyrender == 0.1.1.4
- random >= 1
- optparse-applicative >= 0.14
- arithmoi >= 0.6
- newsynth == 0.3.0.5

library:
  source-dirs: src/lib

executables:
  quantum:
    main: Main.hs
    source-dirs:
    - src/apps/quantum
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - quantum-algorithms
  diagrams:
    main:  Main.hs
    source-dirs:
    - src/apps/diagram
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quantum-algorithms

tests:
  quantum-test:
    main: Main.hs
    source-dirs:
      - src/test
    ghc-options:
      - -threaded
    dependencies:
      - quantum-algorithms
      - tasty
      - tasty-quickcheck
      - tasty-hunit
